# put data here to use as test date while database connestion is set up

mock_data =[
    {
    "id": 1,
    "price": 10.2,
    "stock": 9,
    "title": "Henchman",
    "image": "henchman.jpg",
    "discount": 5,
    "category": "low",
  },
  {
    "id": 2,
    "price": 20.5,
    "stock": 8,
    "title": "Pool of Sharks",
    "image": "shark.jpg",
    "discount": 5,
    "category": "low",
  },
  {
    "id": 3,
    "price": 30.9,
    "stock": 7,
    "title": "Death Ray",
    "image": "ray.jpg",
    "discount": 5,
    "category": "low",
  },
  {
    "id": 4,
    "price": 40.3,
    "stock": 6,
    "title": "Tragic Backstory",
    "image": "sad.jpg",
    "discount": 5,
    "category": "mid",
  },
  {
    "id": 5,
    "price": 50.4,
    "stock": 5,
    "title": "Arch Nemesis' Location",
    "image": "location.jpg",
    "discount": 5,
    "category": "mid",
  },
  {
    "id": 6,
    "price": 60,
    "stock": 4,
    "title": "Hell Hounds",
    "image": "hound.jpg",
    "discount": 5,
    "category": "mid",
  },
  {
    "id": 7,
    "price": 70.7,
    "stock": 3,
    "title": "Pocket Dimension",
    "image": "pocket.jpg",
    "discount": 5,
    "category": "high",
  },
  {
    "id": 8,
    "price": 80,
    "stock": 2,
    "title": "House Cat that Explodes",
    "image": "cat.jpg",
    "discount": 5,
    "category": "high",
  },
  {
    "id": 9,
    "price": 90.9,
    "stock": 1,
    "title": "Evil Lair",
    "image": "lair.jpg",
    "discount": 5,
    "category": "high",
  }
]